In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('dqs_23-24_all.csv', header=[0,1])
df = df.fillna(0)

first_name = ""
new_columns = []
first = True
for name in df.columns:
    if first:
        first = False
        new_col = tuple([first_name, name[1]])
    elif "Unnamed" in name[0]:
        new_col = tuple([first_name, name[1]])
    else:
        first_name = name[0]
        new_col = name
    new_columns.append(new_col)
df.columns = new_columns

school = ('', 'SCHOOL')
rows = ['BASEBALL-V','BASKETBALL-V BOYS','BASKETBALL-V GIRLS','FIELD HOCKEY-V','FOOTBALL-V','GOLF-FALL','GOLF-SPRING','GYMNASTICS',
        'Ice Hockey-V BOYS','Ice Hockey-V GIRLS','INDOOR TRACK','LACROSSE-V BOYS','LACROSSE-V GIRLS','RUGBY BOYS','RUGBY GIRLS',
       'SOCCER-V BOYS','SOCCER-V GIRLS','SOFTBALL-V','SKI','SWIMMING-GIRLS','SWIMMING-BOYS','TENNIS-BOYS','TENNIS-GIRLS',
        'TRACK & FIELD-BOYS','TRACK & FIELD-GIRLS','VOLLEYBALL-V BOYS','VOLLEYBALL-V GIRLS','WRESTLING','X COUNTRY',
        'BASEBALL-V','GOLF-SPRING','LACROSSE-V BOYS','LACROSSE-V GIRLS','RUGBY BOYS','RUGBY GIRLS','SOFTBALL-V','TENNIS-BOYS',
        'TENNIS-GIRLS','TRACK & FIELD-BOYS','TRACK & FIELD-GIRLS','VOLLEYBALL-V BOYS']
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

spring_sports = ['','BASEBALL-V','GOLF-SPRING','LACROSSE-V BOYS','LACROSSE-V GIRLS',
               'RUGBY BOYS','RUGBY GIRLS','SOFTBALL-V','TENNIS-BOYS','TENNIS-GIRLS',
              'TRACK & FIELD-BOYS','TRACK & FIELD-GIRLS','VOLLEYBALL-V BOYS']
other_sports = [val for val in rows if val not in spring_sports]
l = []
for col in df:
    if col[0] not in spring_sports:
        df = df.drop(col, axis=1)
for col in df:
    l.append(col[1])
l = list(set(l))
print(l)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
['Coach', '1 Game', 'SCHOOL', 'Tour', 'MailCITY', '1 yr', '2 Game']

In [2]:
result = pd.DataFrame()

for i in range(df.shape[0]):
    scname = df.iloc[i][school]
    old_name = ''
    for col in df:
        m = [(scname,col[0])]
        if col[1] == '1 Game':
            m.append(df.iloc[i][col])
            m.append(0)
            m.append(0)
            m.append(0)
            m.append(0)
        elif col[1] == '2 Game':
            m.append(0)
            m.append(df.iloc[i][col])
            m.append(0)
            m.append(0)
            m.append(0) 
        elif col[1] == '1 yr':
            m.append(0)
            m.append(0) 
            m.append(df.iloc[i][col])
            m.append(0)
            m.append(0)
        elif col[1] == 'Tour':
            m.append(0)
            m.append(0) 
            m.append(0)
            m.append(df.iloc[i][col])
            m.append(0)
        elif col[1] == 'Coach':
            m.append(0)
            m.append(0) 
            m.append(0)
            m.append(0)
            m.append(df.iloc[i][col])
        else:
            continue
        row = pd.DataFrame([m], columns=['SchoolSport','1 Game','2 Game','1 yr','Tour','Coach'])
        result = pd.concat([result, row], ignore_index=True)
    
# result['Total DQs'] = result.sum(axis=1, numeric_only=True)

In [3]:
res = pd.DataFrame()
for ss in result['SchoolSport'].unique():
    cur = result[result['SchoolSport'] == ss]
    m = [ss[0], ss[1]]
    m.append(cur['1 Game'].sum())
    m.append(cur['2 Game'].sum())
    m.append(cur['1 yr'].sum())
    m.append(cur['Tour'].sum())
    m.append(cur['Coach'].sum())
    mr = pd.DataFrame([m], columns=['School','Sport','1 Game','2 Game','1 yr','Tour','Coach'])
    res = pd.concat([res, mr], ignore_index=True)

In [4]:
df = res
df['Total DQs'] = df.sum(axis=1, numeric_only=True)
df = df.loc[df['Total DQs'] > 1]
print(df)

                                School              Sport  1 Game  2 Game  \
363            Belchertown High School   LACROSSE-V GIRLS     1.0     0.0
768     Cambridge Rindge & Latin Schl.         BASEBALL-V     0.0     2.0
1106      Dighton-Rehoboth Regional HS    LACROSSE-V BOYS     0.0     2.0
1752  Hoosac Valley Middle/High School         BASEBALL-V     0.0     2.0
1802                Hudson High School    LACROSSE-V BOYS     1.0     0.0
2508       Mohawk Trail Regional HS/MS         BASEBALL-V     0.0     1.0
3372                Revere High School         BASEBALL-V     0.0     1.0
3446       Saint Bernard's High School    LACROSSE-V BOYS     0.0     2.0
3902              Stoneham High School    LACROSSE-V BOYS     1.0     0.0
4524             TOTAL SCHOOLS  (FY23)         BASEBALL-V     0.0    19.0
4526             TOTAL SCHOOLS  (FY23)    LACROSSE-V BOYS    11.0    15.0
4527             TOTAL SCHOOLS  (FY23)   LACROSSE-V GIRLS     5.0     3.0
4530             TOTAL SCHOOLS  (FY23)         SOFTBALL-V     3.0     0.0
4535             TOTAL SCHOOLS  (FY23)  VOLLEYBALL-V BOYS     3.0     0.0

      1 yr  Tour  Coach  Total DQs
363    1.0   0.0    0.0        2.0
768    0.0   0.0    0.0        2.0
1106   0.0   0.0    0.0        2.0
1752   1.0   0.0    0.0        3.0
1802   1.0   0.0    0.0        2.0
2508   0.0   0.0    1.0        2.0
3372   0.0   0.0    1.0        2.0
3446   0.0   0.0    0.0        2.0
3902   0.0   0.0    1.0        2.0
4524   1.0   2.0    5.0       27.0
4526   1.0   1.0    4.0       32.0
4527   1.0   1.0    3.0       13.0
4530   0.0   0.0    2.0        5.0
4535   0.0   0.0    0.0        3.0

In [5]:
df = df.loc[df['School'] != 'TOTAL SCHOOLS  (FY23)']
df.reset_index(drop=True, inplace=True)
print(df)

                             School             Sport  1 Game  2 Game  1 yr  \
0           Belchertown High School  LACROSSE-V GIRLS     1.0     0.0   1.0
1    Cambridge Rindge & Latin Schl.        BASEBALL-V     0.0     2.0   0.0
2      Dighton-Rehoboth Regional HS   LACROSSE-V BOYS     0.0     2.0   0.0
3  Hoosac Valley Middle/High School        BASEBALL-V     0.0     2.0   1.0
4                Hudson High School   LACROSSE-V BOYS     1.0     0.0   1.0
5       Mohawk Trail Regional HS/MS        BASEBALL-V     0.0     1.0   0.0
6                Revere High School        BASEBALL-V     0.0     1.0   0.0
7       Saint Bernard's High School   LACROSSE-V BOYS     0.0     2.0   0.0
8              Stoneham High School   LACROSSE-V BOYS     1.0     0.0   0.0

   Tour  Coach  Total DQs
0   0.0    0.0        2.0
1   0.0    0.0        2.0
2   0.0    0.0        2.0
3   0.0    0.0        3.0
4   0.0    0.0        2.0
5   0.0    1.0        2.0
6   0.0    1.0        2.0
7   0.0    0.0        2.0
8   0.0    1.0        2.0

In [6]:
df.to_csv('dqs_s23_varsity.csv')
df_spring = df

In [7]:
import numpy as np
import pandas as pd
df = pd.read_csv('dqs_23-24.csv', header=[0,1])
df = df.fillna(0)

first_name = ""
new_columns = []
first = True
for name in df.columns:
    if first:
        first = False
        new_col = tuple([first_name, name[1]])
    elif "Unnamed" in name[0]:
        new_col = tuple([first_name, name[1]])
    else:
        first_name = name[0]
        new_col = name
    new_columns.append(new_col)
df.columns = new_columns

school = ('', 'SCHOOL')
rows = ['','BASEBALL-V','BASKETBALL-V BOYS','BASKETBALL-V GIRLS','FIELD HOCKEY-V','FOOTBALL-V','GOLF-FALL','GOLF-SPRING','GYMNASTICS',
        'Ice Hockey-V BOYS','Ice Hockey-V GIRLS','INDOOR TRACK','LACROSSE-V BOYS','LACROSSE-V GIRLS','RUGBY BOYS','RUGBY GIRLS',
       'SOCCER-V BOYS','SOCCER-V GIRLS','SOFTBALL-V','SKI','SWIMMING-GIRLS','SWIMMING-BOYS','TENNIS-BOYS','TENNIS-GIRLS',
        'TRACK & FIELD-BOYS','TRACK & FIELD-GIRLS','VOLLEYBALL-V BOYS','VOLLEYBALL-V GIRLS','WRESTLING','X COUNTRY']
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

spring_sports = ['BASEBALL-V','GOLF-SPRING','LACROSSE-V BOYS','LACROSSE-V GIRLS',
               'RUGBY BOYS','RUGBY GIRLS','SOFTBALL-V','TENNIS-BOYS','TENNIS-GIRLS',
              'TRACK & FIELD-BOYS','TRACK & FIELD-GIRLS','VOLLEYBALL-V BOYS']
other_sports = [val for val in rows if val not in spring_sports]
l = []
for col in df:
    if col[0] not in other_sports:
        df = df.drop(col, axis=1)
for col in df:
    l.append(col[1])
l = list(set(l))
print(l)

['Coach', 'District', '1 Game', 'SCHOOL', 'Tour', 'MailCITY', '1 yr', '2 Game']

In [8]:
result = pd.DataFrame()

for i in range(df.shape[0]):
    scname = df.iloc[i][school]
    for col in df:
        m = [(scname,col[0])]
        if col[1] == '1 Game':
            m.append(df.iloc[i][col])
            m.append(0)
            m.append(0)
            m.append(0)
            m.append(0)
        elif col[1] == '2 Game':
            m.append(0)
            m.append(df.iloc[i][col])
            m.append(0)
            m.append(0)
            m.append(0) 
        elif col[1] == '1 yr':
            m.append(0)
            m.append(0) 
            m.append(df.iloc[i][col])
            m.append(0)
            m.append(0)
        elif col[1] == 'Tour':
            m.append(0)
            m.append(0) 
            m.append(0)
            m.append(df.iloc[i][col])
            m.append(0)
        elif col[1] == 'Coach':
            m.append(0)
            m.append(0) 
            m.append(0)
            m.append(0)
            m.append(df.iloc[i][col])
        else:
            continue
        row = pd.DataFrame([m], columns=['SchoolSport','1 Game','2 Game','1 yr','Tour','Coach'])
        result = pd.concat([result, row], ignore_index=True)
    
# result['Total DQs'] = result.sum(axis=1, numeric_only=True)

In [9]:
res = pd.DataFrame()
for ss in result['SchoolSport'].unique():
    cur = result[result['SchoolSport'] == ss]
    m = [ss[0], ss[1]]
    m.append(cur['1 Game'].sum())
    m.append(cur['2 Game'].sum())
    m.append(cur['1 yr'].sum())
    m.append(cur['Tour'].sum())
    m.append(cur['Coach'].sum())
    mr = pd.DataFrame([m], columns=['School','Sport','1 Game','2 Game','1 yr','Tour','Coach'])
    res = pd.concat([res, mr], ignore_index=True)

In [10]:
df = res
df['Total DQs'] = df.sum(axis=1, numeric_only=True)
df = df.loc[df['Total DQs'] > 1]
print(df)

                                   School               Sport  1 Game  2 Game  \
173                   Andover High School          FOOTBALL-V     3.0     0.0
230       Archbishop Williams High School       SOCCER-V BOYS     1.0     0.0
315                     Athol High School       SOCCER-V BOYS     3.0     0.0
434                Barnstable High School       SOCCER-V BOYS     2.0     0.0
533                Bellingham High School   Ice Hockey-V BOYS     1.0     1.0
636             Bishop Feehan High School  Ice Hockey-V GIRLS     0.0     1.0
1057                 Burncoat High School          FOOTBALL-V     1.0     1.0
1233         Central Catholic High School       SOCCER-V BOYS     2.0     0.0
1284                  Chelsea High School       SOCCER-V BOYS     1.0     1.0
1301            Chicopee Comprehensive HS       SOCCER-V BOYS     2.0     0.0
1312                 Chicopee High School          FOOTBALL-V     0.0     2.0
1516             David Prouty High School          FOOTBALL-V     1.0     1.0
1556          Dennis-Yarmouth Regional HS       SOCCER-V BOYS     1.0     1.0
1723              East Boston High School   Ice Hockey-V BOYS     1.0     2.0
1924                 Falmouth High School          FOOTBALL-V     1.0     0.0
2216            Greater New Bedford RVTHS   Ice Hockey-V BOYS     0.0     2.0
2434          Holbrook Middle-High School          FOOTBALL-V     0.0     2.0
2709            King Philip Regional H.S.   Ice Hockey-V BOYS     1.0     1.0
2729         KIPP Academy Lynn Collegiate       SOCCER-V BOYS     1.0     0.0
2797  Lenox Memorial Middle & High School       SOCCER-V BOYS     1.0     0.0
2814               Leominster High School       SOCCER-V BOYS     1.0     0.0
3205              Marlborough High School       SOCCER-V BOYS     0.0     2.0
3936          Nipmuc Regional High School       SOCCER-V BOYS     1.0     1.0
4069            North Reading High School   Ice Hockey-V BOYS     0.0     2.0
4103              Northbridge High School   Ice Hockey-V BOYS     2.0     0.0
4634          Putnam Voc/Tech High School      SOCCER-V GIRLS     1.0     0.0
4834                 Rockport High School   Ice Hockey-V BOYS     0.0     2.0
4868          Saint Bernard's High School   Ice Hockey-V BOYS     1.0     0.0
4956             Saint Mary's High School       SOCCER-V BOYS     2.0     0.0
4970         Saint Paul Diocesan Jr/Sr HS   Ice Hockey-V BOYS     2.0     0.0
5157               Shrewsbury High School   Ice Hockey-V BOYS     1.0     1.0
5314          South High Community School      SOCCER-V GIRLS     2.0     0.0
5372              Southbridge High School   BASKETBALL-V BOYS     0.0     6.0
5392    Southeastern Reg. Voc/Tech School          FOOTBALL-V     1.0     1.0
5466     Springfield Int'l Charter School       SOCCER-V BOYS     2.0     0.0
5585                  Taconic High School       SOCCER-V BOYS     3.0     0.0
6010                Wellesley High School       SOCCER-V BOYS     2.0     0.0
6058         West Springfield High School   Ice Hockey-V BOYS     2.0     0.0
6129                     Westford Academy       SOCCER-V BOYS     2.0     0.0
6375                TOTAL SCHOOLS  (FY24)   BASKETBALL-V BOYS    11.0    10.0
6376                TOTAL SCHOOLS  (FY24)  BASKETBALL-V GIRLS     3.0     2.0
6377                TOTAL SCHOOLS  (FY24)      FIELD HOCKEY-V     1.0     0.0
6378                TOTAL SCHOOLS  (FY24)          FOOTBALL-V    14.0    18.0
6381                TOTAL SCHOOLS  (FY24)   Ice Hockey-V BOYS    37.0    26.0
6382                TOTAL SCHOOLS  (FY24)  Ice Hockey-V GIRLS     1.0     2.0
6384                TOTAL SCHOOLS  (FY24)       SOCCER-V BOYS    72.0    16.0
6385                TOTAL SCHOOLS  (FY24)      SOCCER-V GIRLS    16.0     3.0
6390                TOTAL SCHOOLS  (FY24)           WRESTLING     3.0     2.0

      1 yr  Tour  Coach  Total DQs
173    0.0   0.0    0.0        3.0
230    0.0   1.0    0.0        2.0
315    0.0   0.0    0.0        3.0
434    0.0   0.0    0.0        2.0
533    0.0   0.0    0.0        2.0
636    0.0   1.0    0.0        2.0
1057   0.0   0.0    0.0        2.0
1233   0.0   0.0    0.0        2.0
1284   0.0   0.0    0.0        2.0
1301   0.0   0.0    0.0        2.0
1312   0.0   0.0    0.0        2.0
1516   0.0   0.0    0.0        2.0
1556   0.0   0.0    0.0        2.0
1723   1.0   0.0    0.0        4.0
1924   0.0   1.0    0.0        2.0
2216   0.0   0.0    0.0        2.0
2434   0.0   0.0    0.0        2.0
2709   0.0   0.0    0.0        2.0
2729   0.0   1.0    0.0        2.0
2797   0.0   1.0    1.0        3.0
2814   0.0   1.0    0.0        2.0
3205   0.0   0.0    0.0        2.0
3936   0.0   0.0    0.0        2.0
4069   0.0   0.0    0.0        2.0
4103   0.0   0.0    0.0        2.0
4634   1.0   0.0    0.0        2.0
4834   0.0   0.0    0.0        2.0
4868   1.0   0.0    0.0        2.0
4956   0.0   0.0    0.0        2.0
4970   0.0   0.0    0.0        2.0
5157   0.0   0.0    0.0        2.0
5314   0.0   0.0    0.0        2.0
5372   0.0   0.0    0.0        6.0
5392   0.0   0.0    0.0        2.0
5466   0.0   0.0    0.0        2.0
5585   0.0   0.0    0.0        3.0
6010   0.0   0.0    0.0        2.0
6058   0.0   0.0    0.0        2.0
6129   0.0   0.0    0.0        2.0
6375   0.0   0.0    7.0       28.0
6376   0.0   0.0    2.0        7.0
6377   0.0   1.0    0.0        2.0
6378   0.0   4.0    1.0       37.0
6381   5.0   1.0    0.0       69.0
6382   0.0   2.0    1.0        6.0
6384   1.0   8.0    5.0      102.0
6385   1.0   0.0    2.0       22.0
6390   0.0   2.0    1.0        8.0

In [11]:
df = df.loc[df['School'] != 'TOTAL SCHOOLS  (FY24)']
df.reset_index(drop=True, inplace=True)
print(df)

                                 School               Sport  1 Game  2 Game  \
0                   Andover High School          FOOTBALL-V     3.0     0.0
1       Archbishop Williams High School       SOCCER-V BOYS     1.0     0.0
2                     Athol High School       SOCCER-V BOYS     3.0     0.0
3                Barnstable High School       SOCCER-V BOYS     2.0     0.0
4                Bellingham High School   Ice Hockey-V BOYS     1.0     1.0
5             Bishop Feehan High School  Ice Hockey-V GIRLS     0.0     1.0
6                  Burncoat High School          FOOTBALL-V     1.0     1.0
7          Central Catholic High School       SOCCER-V BOYS     2.0     0.0
8                   Chelsea High School       SOCCER-V BOYS     1.0     1.0
9             Chicopee Comprehensive HS       SOCCER-V BOYS     2.0     0.0
10                 Chicopee High School          FOOTBALL-V     0.0     2.0
11             David Prouty High School          FOOTBALL-V     1.0     1.0
12          Dennis-Yarmouth Regional HS       SOCCER-V BOYS     1.0     1.0
13              East Boston High School   Ice Hockey-V BOYS     1.0     2.0
14                 Falmouth High School          FOOTBALL-V     1.0     0.0
15            Greater New Bedford RVTHS   Ice Hockey-V BOYS     0.0     2.0
16          Holbrook Middle-High School          FOOTBALL-V     0.0     2.0
17            King Philip Regional H.S.   Ice Hockey-V BOYS     1.0     1.0
18         KIPP Academy Lynn Collegiate       SOCCER-V BOYS     1.0     0.0
19  Lenox Memorial Middle & High School       SOCCER-V BOYS     1.0     0.0
20               Leominster High School       SOCCER-V BOYS     1.0     0.0
21              Marlborough High School       SOCCER-V BOYS     0.0     2.0
22          Nipmuc Regional High School       SOCCER-V BOYS     1.0     1.0
23            North Reading High School   Ice Hockey-V BOYS     0.0     2.0
24              Northbridge High School   Ice Hockey-V BOYS     2.0     0.0
25          Putnam Voc/Tech High School      SOCCER-V GIRLS     1.0     0.0
26                 Rockport High School   Ice Hockey-V BOYS     0.0     2.0
27          Saint Bernard's High School   Ice Hockey-V BOYS     1.0     0.0
28             Saint Mary's High School       SOCCER-V BOYS     2.0     0.0
29         Saint Paul Diocesan Jr/Sr HS   Ice Hockey-V BOYS     2.0     0.0
30               Shrewsbury High School   Ice Hockey-V BOYS     1.0     1.0
31          South High Community School      SOCCER-V GIRLS     2.0     0.0
32              Southbridge High School   BASKETBALL-V BOYS     0.0     6.0
33    Southeastern Reg. Voc/Tech School          FOOTBALL-V     1.0     1.0
34     Springfield Int'l Charter School       SOCCER-V BOYS     2.0     0.0
35                  Taconic High School       SOCCER-V BOYS     3.0     0.0
36                Wellesley High School       SOCCER-V BOYS     2.0     0.0
37         West Springfield High School   Ice Hockey-V BOYS     2.0     0.0
38                     Westford Academy       SOCCER-V BOYS     2.0     0.0

    1 yr  Tour  Coach  Total DQs
0    0.0   0.0    0.0        3.0
1    0.0   1.0    0.0        2.0
2    0.0   0.0    0.0        3.0
3    0.0   0.0    0.0        2.0
4    0.0   0.0    0.0        2.0
5    0.0   1.0    0.0        2.0
6    0.0   0.0    0.0        2.0
7    0.0   0.0    0.0        2.0
8    0.0   0.0    0.0        2.0
9    0.0   0.0    0.0        2.0
10   0.0   0.0    0.0        2.0
11   0.0   0.0    0.0        2.0
12   0.0   0.0    0.0        2.0
13   1.0   0.0    0.0        4.0
14   0.0   1.0    0.0        2.0
15   0.0   0.0    0.0        2.0
16   0.0   0.0    0.0        2.0
17   0.0   0.0    0.0        2.0
18   0.0   1.0    0.0        2.0
19   0.0   1.0    1.0        3.0
20   0.0   1.0    0.0        2.0
21   0.0   0.0    0.0        2.0
22   0.0   0.0    0.0        2.0
23   0.0   0.0    0.0        2.0
24   0.0   0.0    0.0        2.0
25   1.0   0.0    0.0        2.0
26   0.0   0.0    0.0        2.0
27   1.0   0.0    0.0        2.0
28   0.0   0.0    0.0        2.0
29   0.0   0.0    0.0        2.0
30   0.0   0.0    0.0        2.0
31   0.0   0.0    0.0        2.0
32   0.0   0.0    0.0        6.0
33   0.0   0.0    0.0        2.0
34   0.0   0.0    0.0        2.0
35   0.0   0.0    0.0        3.0
36   0.0   0.0    0.0        2.0
37   0.0   0.0    0.0        2.0
38   0.0   0.0    0.0        2.0

In [12]:
df.to_csv('dqs_f23w24_varsity.csv')
df_fw = df

In [13]:
df_all = pd.concat([df_spring, df_fw], ignore_index=True)

In [14]:
print(df_all)

                                 School               Sport  1 Game  2 Game  \
0               Belchertown High School    LACROSSE-V GIRLS     1.0     0.0
1        Cambridge Rindge & Latin Schl.          BASEBALL-V     0.0     2.0
2          Dighton-Rehoboth Regional HS     LACROSSE-V BOYS     0.0     2.0
3      Hoosac Valley Middle/High School          BASEBALL-V     0.0     2.0
4                    Hudson High School     LACROSSE-V BOYS     1.0     0.0
5           Mohawk Trail Regional HS/MS          BASEBALL-V     0.0     1.0
6                    Revere High School          BASEBALL-V     0.0     1.0
7           Saint Bernard's High School     LACROSSE-V BOYS     0.0     2.0
8                  Stoneham High School     LACROSSE-V BOYS     1.0     0.0
9                   Andover High School          FOOTBALL-V     3.0     0.0
10      Archbishop Williams High School       SOCCER-V BOYS     1.0     0.0
11                    Athol High School       SOCCER-V BOYS     3.0     0.0
12               Barnstable High School       SOCCER-V BOYS     2.0     0.0
13               Bellingham High School   Ice Hockey-V BOYS     1.0     1.0
14            Bishop Feehan High School  Ice Hockey-V GIRLS     0.0     1.0
15                 Burncoat High School          FOOTBALL-V     1.0     1.0
16         Central Catholic High School       SOCCER-V BOYS     2.0     0.0
17                  Chelsea High School       SOCCER-V BOYS     1.0     1.0
18            Chicopee Comprehensive HS       SOCCER-V BOYS     2.0     0.0
19                 Chicopee High School          FOOTBALL-V     0.0     2.0
20             David Prouty High School          FOOTBALL-V     1.0     1.0
21          Dennis-Yarmouth Regional HS       SOCCER-V BOYS     1.0     1.0
22              East Boston High School   Ice Hockey-V BOYS     1.0     2.0
23                 Falmouth High School          FOOTBALL-V     1.0     0.0
24            Greater New Bedford RVTHS   Ice Hockey-V BOYS     0.0     2.0
25          Holbrook Middle-High School          FOOTBALL-V     0.0     2.0
26            King Philip Regional H.S.   Ice Hockey-V BOYS     1.0     1.0
27         KIPP Academy Lynn Collegiate       SOCCER-V BOYS     1.0     0.0
28  Lenox Memorial Middle & High School       SOCCER-V BOYS     1.0     0.0
29               Leominster High School       SOCCER-V BOYS     1.0     0.0
30              Marlborough High School       SOCCER-V BOYS     0.0     2.0
31          Nipmuc Regional High School       SOCCER-V BOYS     1.0     1.0
32            North Reading High School   Ice Hockey-V BOYS     0.0     2.0
33              Northbridge High School   Ice Hockey-V BOYS     2.0     0.0
34          Putnam Voc/Tech High School      SOCCER-V GIRLS     1.0     0.0
35                 Rockport High School   Ice Hockey-V BOYS     0.0     2.0
36          Saint Bernard's High School   Ice Hockey-V BOYS     1.0     0.0
37             Saint Mary's High School       SOCCER-V BOYS     2.0     0.0
38         Saint Paul Diocesan Jr/Sr HS   Ice Hockey-V BOYS     2.0     0.0
39               Shrewsbury High School   Ice Hockey-V BOYS     1.0     1.0
40          South High Community School      SOCCER-V GIRLS     2.0     0.0
41              Southbridge High School   BASKETBALL-V BOYS     0.0     6.0
42    Southeastern Reg. Voc/Tech School          FOOTBALL-V     1.0     1.0
43     Springfield Int'l Charter School       SOCCER-V BOYS     2.0     0.0
44                  Taconic High School       SOCCER-V BOYS     3.0     0.0
45                Wellesley High School       SOCCER-V BOYS     2.0     0.0
46         West Springfield High School   Ice Hockey-V BOYS     2.0     0.0
47                     Westford Academy       SOCCER-V BOYS     2.0     0.0

    1 yr  Tour  Coach  Total DQs
0    1.0   0.0    0.0        2.0
1    0.0   0.0    0.0        2.0
2    0.0   0.0    0.0        2.0
3    1.0   0.0    0.0        3.0
4    1.0   0.0    0.0        2.0
5    0.0   0.0    1.0        2.0
6    0.0   0.0    1.0        2.0
7    0.0   0.0    0.0        2.0
8    0.0   0.0    1.0        2.0
9    0.0   0.0    0.0        3.0
10   0.0   1.0    0.0        2.0
11   0.0   0.0    0.0        3.0
12   0.0   0.0    0.0        2.0
13   0.0   0.0    0.0        2.0
14   0.0   1.0    0.0        2.0
15   0.0   0.0    0.0        2.0
16   0.0   0.0    0.0        2.0
17   0.0   0.0    0.0        2.0
18   0.0   0.0    0.0        2.0
19   0.0   0.0    0.0        2.0
20   0.0   0.0    0.0        2.0
21   0.0   0.0    0.0        2.0
22   1.0   0.0    0.0        4.0
23   0.0   1.0    0.0        2.0
24   0.0   0.0    0.0        2.0
25   0.0   0.0    0.0        2.0
26   0.0   0.0    0.0        2.0
27   0.0   1.0    0.0        2.0
28   0.0   1.0    1.0        3.0
29   0.0   1.0    0.0        2.0
30   0.0   0.0    0.0        2.0
31   0.0   0.0    0.0        2.0
32   0.0   0.0    0.0        2.0
33   0.0   0.0    0.0        2.0
34   1.0   0.0    0.0        2.0
35   0.0   0.0    0.0        2.0
36   1.0   0.0    0.0        2.0
37   0.0   0.0    0.0        2.0
38   0.0   0.0    0.0        2.0
39   0.0   0.0    0.0        2.0
40   0.0   0.0    0.0        2.0
41   0.0   0.0    0.0        6.0
42   0.0   0.0    0.0        2.0
43   0.0   0.0    0.0        2.0
44   0.0   0.0    0.0        3.0
45   0.0   0.0    0.0        2.0
46   0.0   0.0    0.0        2.0
47   0.0   0.0    0.0        2.0

In [15]:
df_all = df_all.sort_values('School', ignore_index=True)
print(df_all)

                                 School               Sport  1 Game  2 Game  \
0                   Andover High School          FOOTBALL-V     3.0     0.0
1       Archbishop Williams High School       SOCCER-V BOYS     1.0     0.0
2                     Athol High School       SOCCER-V BOYS     3.0     0.0
3                Barnstable High School       SOCCER-V BOYS     2.0     0.0
4               Belchertown High School    LACROSSE-V GIRLS     1.0     0.0
5                Bellingham High School   Ice Hockey-V BOYS     1.0     1.0
6             Bishop Feehan High School  Ice Hockey-V GIRLS     0.0     1.0
7                  Burncoat High School          FOOTBALL-V     1.0     1.0
8        Cambridge Rindge & Latin Schl.          BASEBALL-V     0.0     2.0
9          Central Catholic High School       SOCCER-V BOYS     2.0     0.0
10                  Chelsea High School       SOCCER-V BOYS     1.0     1.0
11            Chicopee Comprehensive HS       SOCCER-V BOYS     2.0     0.0
12                 Chicopee High School          FOOTBALL-V     0.0     2.0
13             David Prouty High School          FOOTBALL-V     1.0     1.0
14          Dennis-Yarmouth Regional HS       SOCCER-V BOYS     1.0     1.0
15         Dighton-Rehoboth Regional HS     LACROSSE-V BOYS     0.0     2.0
16              East Boston High School   Ice Hockey-V BOYS     1.0     2.0
17                 Falmouth High School          FOOTBALL-V     1.0     0.0
18            Greater New Bedford RVTHS   Ice Hockey-V BOYS     0.0     2.0
19          Holbrook Middle-High School          FOOTBALL-V     0.0     2.0
20     Hoosac Valley Middle/High School          BASEBALL-V     0.0     2.0
21                   Hudson High School     LACROSSE-V BOYS     1.0     0.0
22         KIPP Academy Lynn Collegiate       SOCCER-V BOYS     1.0     0.0
23            King Philip Regional H.S.   Ice Hockey-V BOYS     1.0     1.0
24  Lenox Memorial Middle & High School       SOCCER-V BOYS     1.0     0.0
25               Leominster High School       SOCCER-V BOYS     1.0     0.0
26              Marlborough High School       SOCCER-V BOYS     0.0     2.0
27          Mohawk Trail Regional HS/MS          BASEBALL-V     0.0     1.0
28          Nipmuc Regional High School       SOCCER-V BOYS     1.0     1.0
29            North Reading High School   Ice Hockey-V BOYS     0.0     2.0
30              Northbridge High School   Ice Hockey-V BOYS     2.0     0.0
31          Putnam Voc/Tech High School      SOCCER-V GIRLS     1.0     0.0
32                   Revere High School          BASEBALL-V     0.0     1.0
33                 Rockport High School   Ice Hockey-V BOYS     0.0     2.0
34          Saint Bernard's High School   Ice Hockey-V BOYS     1.0     0.0
35          Saint Bernard's High School     LACROSSE-V BOYS     0.0     2.0
36             Saint Mary's High School       SOCCER-V BOYS     2.0     0.0
37         Saint Paul Diocesan Jr/Sr HS   Ice Hockey-V BOYS     2.0     0.0
38               Shrewsbury High School   Ice Hockey-V BOYS     1.0     1.0
39          South High Community School      SOCCER-V GIRLS     2.0     0.0
40              Southbridge High School   BASKETBALL-V BOYS     0.0     6.0
41    Southeastern Reg. Voc/Tech School          FOOTBALL-V     1.0     1.0
42     Springfield Int'l Charter School       SOCCER-V BOYS     2.0     0.0
43                 Stoneham High School     LACROSSE-V BOYS     1.0     0.0
44                  Taconic High School       SOCCER-V BOYS     3.0     0.0
45                Wellesley High School       SOCCER-V BOYS     2.0     0.0
46         West Springfield High School   Ice Hockey-V BOYS     2.0     0.0
47                     Westford Academy       SOCCER-V BOYS     2.0     0.0

    1 yr  Tour  Coach  Total DQs
0    0.0   0.0    0.0        3.0
1    0.0   1.0    0.0        2.0
2    0.0   0.0    0.0        3.0
3    0.0   0.0    0.0        2.0
4    1.0   0.0    0.0        2.0
5    0.0   0.0    0.0        2.0
6    0.0   1.0    0.0        2.0
7    0.0   0.0    0.0        2.0
8    0.0   0.0    0.0        2.0
9    0.0   0.0    0.0        2.0
10   0.0   0.0    0.0        2.0
11   0.0   0.0    0.0        2.0
12   0.0   0.0    0.0        2.0
13   0.0   0.0    0.0        2.0
14   0.0   0.0    0.0        2.0
15   0.0   0.0    0.0        2.0
16   1.0   0.0    0.0        4.0
17   0.0   1.0    0.0        2.0
18   0.0   0.0    0.0        2.0
19   0.0   0.0    0.0        2.0
20   1.0   0.0    0.0        3.0
21   1.0   0.0    0.0        2.0
22   0.0   1.0    0.0        2.0
23   0.0   0.0    0.0        2.0
24   0.0   1.0    1.0        3.0
25   0.0   1.0    0.0        2.0
26   0.0   0.0    0.0        2.0
27   0.0   0.0    1.0        2.0
28   0.0   0.0    0.0        2.0
29   0.0   0.0    0.0        2.0
30   0.0   0.0    0.0        2.0
31   1.0   0.0    0.0        2.0
32   0.0   0.0    1.0        2.0
33   0.0   0.0    0.0        2.0
34   1.0   0.0    0.0        2.0
35   0.0   0.0    0.0        2.0
36   0.0   0.0    0.0        2.0
37   0.0   0.0    0.0        2.0
38   0.0   0.0    0.0        2.0
39   0.0   0.0    0.0        2.0
40   0.0   0.0    0.0        6.0
41   0.0   0.0    0.0        2.0
42   0.0   0.0    0.0        2.0
43   0.0   0.0    1.0        2.0
44   0.0   0.0    0.0        3.0
45   0.0   0.0    0.0        2.0
46   0.0   0.0    0.0        2.0
47   0.0   0.0    0.0        2.0

In [16]:
df_all.to_csv('dqs_sf23-w24_varsity.csv')